[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  # Thư viện cho GPS u-blox
  mikalhart/TinyGPSPlus @ ^1.0.3
  # Thư viện giao tiếp nối tiếp mềm cho GPS
  plerup/EspSoftwareSerial @ ^8.1.0
  # Thư viện điều khiển dải LED cảnh báo
  fastled/FastLED @ ^3.6.0
  # Thư viện hỗ trợ JSON cho việc trao đổi dữ liệu với Jetson/Cloud
  bblanchon/ArduinoJson @ ^6.21.3
